### ISSUE TITLE
Handle case where class name matches property name

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/js_facade_gen#20]
Some definition files use property names that are the same as the generated class name ([aws-sdk.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/aws-sdk/aws-sdk.d.ts) for instance).  For example, to avoid analyzer warnings:

```
  external Credentials get Credentials;
  external set Credentials(Credentials v);
```

is generated, and needs to be changed (by hand) to 

```
  external CredentialsType get Credentials;
  external set Credentials(CredentialsType v);
```

**Comment by jacob314** [comment]
What do you think of instead of renaming the type renaming the method?
I can automatically rename the method from
external Credentials get Credentials;
to 
external Credentials get JS$Credentials;
for cases where the class name and method name conflict.

**Comment by jacob314** [comment]
Generally, renaming the class would cause a ton of renames but renaming just the method should be more localized.

**Comment by jacob314** [comment]
Actually there is a cleaner fix. No names need to change. We just need to import the current library with a prefix to avoid ambiguity. I will make the code generator do this manually but for now:

Try this manual edit of the generated file:

import "aws_sdk.dart" as aws_sdk;

  external aws_sdk.Credentials get Credentials;
  external set Credentials(aws_sdk.Credentials v);

**Comment by johnpryan** [comment]
awesome - that's a nice solution

**Comment by thosakwe** [comment]
Should this issue be closed?

**Comment by johnpryan** [comment]
yep! closing

**Comment by johnpryan** [comment]
Although thinking more about this... manual edits are probably not the ideal solution
