### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by sjuxax** [dart-lang/js_facade_gen#29]
Despite several bug reports, no changes to this repository have been pushed since last October. The few libraries I tried to convert have failed. Are there plans to fix this? I was really excited about the possibility of converting from TypeScript definitions to Dart. Without it, Dart becomes a much less serious prospect.

**Comment by rickbsgu** [comment]
Second the question.

**Comment by kevmoo** [comment]
JS interop is important, but we've been in a holding pattern while we work on the Dart 2 effort – http://news.dartlang.org/2017/08/getting-your-apps-ready-for-dart-20.html.

The existing interop story had to be compatible with Dartium – which made a number of things more difficult.

This restriction goes away with Dart2, but we need to get our compilers and other infrastructure aligned before we dig in here again.

We haven't forgotten about this package or the overall interop story – we're just focusing on foundational things first.

Thanks for your patience!

**Comment by rickbsgu** [comment]
Ok, I guess I'm going to punt for now and do next effort in a JS framework.  See where this (and other efforts) are at the end of that.

thx.

**Comment by kevmoo** [comment]
@rickbsgu (and @sjuxax ) feel free to email me directly [github alias] [at] google.com

Happy to dig into specific scenarios.
