### ISSUE TITLE
Conflicting Constructor Definitions

### ISSUE THREAD

**Issue by derekxu16** [dart-lang/js_facade_gen#38]
TypeScript's dom.generated.d.ts file has several class definitions of this form:
```
declare var X: {prototype: X; new (): X;};

interface X {
  readonly a: string;
}
```

When met with this the facade generator current generates:
```
@JS("X")
abstract class X {
  external String get a;
  external static X get prototype;
  external static set prototype(X v);
  external factory X();
  external factory X({String a});
}
```
This happens because new() is a member of X but it's also a ConstructSignature node. Which constructor should be emitted in cases like this, the default constructor or the one with named parameters?

**Comment by derekxu16** [comment]
Also should we avoid emitting getters and setters for `prototype`?

**Comment by jacob314** [comment]
We should suppress `prototype` member

We should remove the one with the named parameter. That one is what we generate for a plain interface but in this case it appears the intent is that you should actually call the specific real constructor to instantiate the class.
